[project]
name = "agent-harness"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Aayush Man Shrestha", email = "aayush.m.shrestha@gmail.com" }
]
requires-python = ">=3.14 "
dependencies = [
    "click>=8.5.0",
    "openai>=3.16.2",
    "pydantic>=2.13.5",
    "python-dotenv>=1.2.3",
    "rich>=15.0.0",
    "tiktoken>=0.14.0",
]
